### ISSUE TITLE
[bug] runtime error when calling `interpolated_inversion`

### ISSUE THREAD

**Issue by linoytsaban** [DarkMnDragon/rf-inversion-diffuser#1]
Thanks for sharing your implementation! 

I'm encountering an issue when running the notebook, maybe you can help: 

1. I made no changes to the notebook except for one to change the path of the model to be `"black-forest-labs/FLUX.1-dev"`

2. when getting to `interpolated_inversion`, running this: 
```
gamma = 0.5
img_latent_inv = interpolated_inversion(pipe, img_latent, gamma, DTYPE, use_shift_t_sampling=True)
```
leads to - 
```
RuntimeError: The size of tensor a (4608) must match the size of tensor b (16896) at non-singleton dimension 2
```

Does it look familiar? 

**versions:**
Torch version: 2.4.0+cu124
Diffusers version: 0.32.0.dev0
Transformers version: 4.44.1

**Comment by CyberDragon93** [comment]
Hi @linoytsaban, I haven’t encountered this issue before. Could you provide more detailed error information, such as the specific lines of code where it occurs?

**Comment by linoytsaban** [comment]
For simplicity, I also tried running the .py file and I'm getting the same error so maybe it's my env 

```
!python inversion_editing_cli.py \
  --model_path="black-forest-labs/FLUX.1-dev"\
  --use_inversed_latents
```

leads to - 

```
Traceback (most recent call last):
  File "/home/ubuntu/rf-inversion-diffuser/inversion_editing_cli.py", line 351, in <module>
    main()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/rf-inversion-diffuser/inversion_editing_cli.py", line 321, in main
    inversed_latent = interpolated_inversion(pipe, img_latent, gamma=args.gamma, DTYPE=DTYPE, num_steps=args.num_steps, use_shift_t_sampling=False)    
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/rf-inversion-diffuser/inversion_editing_cli.py", line 95, in interpolated_inversion
    flux_velocity = pipeline.transformer(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/diffusers/models/transformers/transformer_flux.py", line 500, in forward
    encoder_hidden_states, hidden_states = block(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/diffusers/models/transformers/transformer_flux.py", line 175, in forward
    attn_output, context_attn_output = self.attn(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 495, in forward
    return self.processor(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 1778, in __call__
    query = apply_rotary_emb(query, image_rotary_emb)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/diffusers/models/embeddings.py", line 734, in apply_rotary_emb
    out = (x.float() * cos + x_rotated.float() * sin).to(x.dtype)
RuntimeError: The size of tensor a (4608) must match the size of tensor b (16896) at non-singleton dimension 2
```

**Comment by CyberDragon93** [comment]
That's strange, I asked few of my friends, they didn't encounter the same issue

**Comment by mxteaw** [comment]
> For simplicity, I also tried running the .py file and I'm getting the same error so maybe it's my env
> 
> ```
> !python inversion_editing_cli.py \
>   --model_path="black-forest-labs/FLUX.1-dev"\
>   --use_inversed_latents
> ```
> 
> leads to -
> 
> ```
> Traceback (most recent call last):
>   File "/home/ubuntu/rf-inversion-diffuser/inversion_editing_cli.py", line 351, in <module>
>     main()
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/ubuntu/rf-inversion-diffuser/inversion_editing_cli.py", line 321, in main
>     inversed_latent = interpolated_inversion(pipe, img_latent, gamma=args.gamma, DTYPE=DTYPE, num_steps=args.num_steps, use_shift_t_sampling=False)    
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/ubuntu/rf-inversion-diffuser/inversion_editing_cli.py", line 95, in interpolated_inversion
>     flux_velocity = pipeline.transformer(
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/diffusers/models/transformers/transformer_flux.py", line 500, in forward
>     encoder_hidden_states, hidden_states = block(
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/diffusers/models/transformers/transformer_flux.py", line 175, in forward
>     attn_output, context_attn_output = self.attn(
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 495, in forward
>     return self.processor(
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 1778, in __call__
>     query = apply_rotary_emb(query, image_rotary_emb)
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/diffusers/models/embeddings.py", line 734, in apply_rotary_emb
>     out = (x.float() * cos + x_rotated.float() * sin).to(x.dtype)
> RuntimeError: The size of tensor a (4608) must match the size of tensor b (16896) at non-singleton dimension 2
> ```

I'm having the same issue as you.Did you solve this problem?

**Comment by CyberDragon93** [comment]
Hi @mxteaw, can you use debug mode to identify what component causes this mismatch? Maybe try to print all the tensors shape, I can help check on that

**Comment by mxteaw** [comment]
> Hi @mxteaw, can you use debug mode to identify what component causes this mismatch? Maybe try to print all the tensors shape, I can help check on that

会debug但不是很熟练,昨天只debug看了一眼latents的张量形状，但是也看不太懂。昨天晚上不小心把dev模型删了还在下载中，可以先加您个微信吗？mx4952

**Comment by wuyou22s** [comment]
@mxteaw Try Diffusers-0.30.2

**Comment by CyberDragon93** [comment]
Cool, @mxteaw did you fix that?
